/*
    Copyright (c) 2020 Erxl
    Ordinary.GenBitField is licensed under Mulan PSL v2.
    You can use this software according to the terms and conditions of the Mulan PSL v2.
    You may obtain a copy of Mulan PSL v2 at:
             http://license.coscl.org.cn/MulanPSL2
    THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
    See the Mulan PSL v2 for more details.
*/

using Microsoft.VisualStudio.TestTools.UnitTesting;
using Ordinary;
using System;

namespace Test
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var a = new MyStruct();
            a.a = 33333;
            a.b = 15553355;
            a.c = 99999999999999999;
            a.d = (uint24)0;
            a.e = 42244;
            a.f = 4224;
            a.g = 33;
            a.h = 123;
            a.i = 3553553;
            a.j = 3535133;
            a.k = 33554431;
            Assert.AreEqual(a.a, (uint)33333);
            Assert.AreEqual(a.b, 15553355);
            Assert.AreEqual(a.c, (long)99999999999999999);
            Assert.AreEqual(a.d, (uint24)0);
            Assert.AreEqual(a.e, 42244);
            Assert.AreEqual(a.f, (short)4224);
            Assert.AreEqual(a.g, (byte)33);
            Assert.AreEqual(a.h, (sbyte)123);
            Assert.AreEqual(a.i, (ulong)3553553);
            Assert.AreEqual(a.j, (uint)3535133);
            Assert.AreEqual(a.k, (uint)33554431);
        }
    }

    internal unsafe struct MyStruct
    {
        private byte byte0, byte1, byte2, byte3, byte4, byte5, byte6, byte7, byte8, byte9, byte10, byte11, byte12, byte13, byte14, byte15, byte16, byte17, byte18, byte19, byte20, byte21, byte22, byte23, byte24, byte25, byte26, byte27, byte28, byte29, byte30, byte31, byte32, byte33, byte34, byte35, byte36, byte37, byte38, byte39, byte40, byte41, byte42, byte43, byte44, byte45, byte46, byte47, byte48, byte49, byte50, byte51, byte52, byte53, byte54, byte55, byte56, byte57, byte58, byte59, byte60, byte61, byte62, byte63, byte64, byte65, byte66, byte67, byte68, byte69, byte70, byte71, byte72, byte73, byte74, byte75, byte76, byte77, byte78; public uint a { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte0; *((byte*)bufsrc + 1) = byte1; buf2 = buf1 >> 0; return *(uint*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(uint*)bufsrc = value; byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; } }
        public int b { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte2; *((byte*)bufsrc + 1) = byte3; *((byte*)bufsrc + 2) = byte4; *((byte*)bufsrc + 3) = (byte)(byte5 & 1); buf2 = buf1 >> 0; return *(int*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(int*)bufsrc = value; *((byte*)bufdst + 3) |= (byte)(byte6 & 254); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; } }
        public long c { get { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *((byte*)bufsrc + 0) = byte5; *((byte*)bufsrc + 1) = byte6; *((byte*)bufsrc + 2) = byte7; *((byte*)bufsrc + 3) = byte8; *((byte*)bufsrc + 4) = byte9; *((byte*)bufsrc + 5) = byte10; *((byte*)bufsrc + 6) = byte11; *((byte*)bufsrc + 7) = (byte)(byte12 & 3); buf2 = buf1 >> 1; return *(long*)bufdst; } set { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *(long*)bufsrc = value; buf2 = buf1 << 1; *(byte*)bufdst |= (byte)(byte5 & 1); *((byte*)bufdst + 7) |= (byte)(byte13 & 252); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; byte4 = ((byte*)bufdst)[4]; byte5 = ((byte*)bufdst)[5]; byte6 = ((byte*)bufdst)[6]; byte7 = ((byte*)bufdst)[7]; } }
        public uint24 d { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte12; *((byte*)bufsrc + 1) = byte13; *((byte*)bufsrc + 2) = byte14; *((byte*)bufsrc + 3) = (byte)(byte15 & 3); buf2 = buf1 >> 2; return *(uint24*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(uint24*)bufsrc = value; buf2 = buf1 << 2; *(byte*)bufdst |= (byte)(byte12 & 3); *((byte*)bufdst + 3) |= (byte)(byte16 & 252); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; } }
        public int e { get { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *((byte*)bufsrc + 0) = byte15; *((byte*)bufsrc + 1) = byte16; *((byte*)bufsrc + 2) = byte17; *((byte*)bufsrc + 3) = byte18; *((byte*)bufsrc + 4) = (byte)(byte19 & 3); buf2 = buf1 >> 2; return *(int*)bufdst; } set { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *(int*)bufsrc = value; buf2 = buf1 << 2; *(byte*)bufdst |= (byte)(byte15 & 3); *((byte*)bufdst + 4) |= (byte)(byte20 & 252); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; byte4 = ((byte*)bufdst)[4]; } }
        public short f { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte19; *((byte*)bufsrc + 1) = byte20; *((byte*)bufsrc + 2) = (byte)(byte21 & 3); buf2 = buf1 >> 2; return *(short*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(short*)bufsrc = value; buf2 = buf1 << 2; *(byte*)bufdst |= (byte)(byte19 & 3); *((byte*)bufdst + 2) |= (byte)(byte22 & 252); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; } }
        public byte g { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte21; *((byte*)bufsrc + 1) = (byte)(byte22 & 3); buf2 = buf1 >> 2; return *(byte*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(byte*)bufsrc = value; buf2 = buf1 << 2; *(byte*)bufdst |= (byte)(byte21 & 3); *((byte*)bufdst + 1) |= (byte)(byte23 & 252); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; } }
        public sbyte h { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte22; *((byte*)bufsrc + 1) = (byte)(byte23 & 3); buf2 = buf1 >> 2; return *(sbyte*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(sbyte*)bufsrc = value; buf2 = buf1 << 2; *(byte*)bufdst |= (byte)(byte22 & 3); *((byte*)bufdst + 1) |= (byte)(byte24 & 252); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; } }
        public ulong i { get { uint128 buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *((byte*)bufsrc + 0) = byte23; *((byte*)bufsrc + 1) = byte24; *((byte*)bufsrc + 2) = byte25; *((byte*)bufsrc + 3) = byte26; *((byte*)bufsrc + 4) = byte27; *((byte*)bufsrc + 5) = byte28; *((byte*)bufsrc + 6) = byte29; *((byte*)bufsrc + 7) = byte30; *((byte*)bufsrc + 8) = (byte)(byte31 & 3); buf2 = buf1 >> 2; return *(ulong*)bufdst; } set { uint128 buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *(ulong*)bufsrc = value; buf2 = buf1 << 2; *(byte*)bufdst |= (byte)(byte23 & 3); *((byte*)bufdst + 8) |= (byte)(byte32 & 252); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; byte4 = ((byte*)bufdst)[4]; byte5 = ((byte*)bufdst)[5]; byte6 = ((byte*)bufdst)[6]; byte7 = ((byte*)bufdst)[7]; byte8 = ((byte*)bufdst)[8]; } }
        public uint j { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte31; *((byte*)bufsrc + 1) = byte32; *((byte*)bufsrc + 2) = byte33; *((byte*)bufsrc + 3) = (byte)(byte34 & 3); buf2 = buf1 >> 2; return *(uint*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(uint*)bufsrc = value; buf2 = buf1 << 2; *(byte*)bufdst |= (byte)(byte31 & 3); *((byte*)bufdst + 3) |= (byte)(byte35 & 252); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; } }
        public uint k { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte34; *((byte*)bufsrc + 1) = byte35; *((byte*)bufsrc + 2) = byte36; *((byte*)bufsrc + 3) = (byte)(byte37 & 7); buf2 = buf1 >> 2; return *(uint*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(uint*)bufsrc = value; buf2 = buf1 << 2; *(byte*)bufdst |= (byte)(byte34 & 3); *((byte*)bufdst + 3) |= (byte)(byte38 & 248); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; } }
        public ulong l { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte37; *((byte*)bufsrc + 1) = byte38; *((byte*)bufsrc + 2) = byte39; *((byte*)bufsrc + 3) = (byte)(byte40 & 7); buf2 = buf1 >> 3; return *(ulong*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(ulong*)bufsrc = value; buf2 = buf1 << 3; *(byte*)bufdst |= (byte)(byte37 & 7); *((byte*)bufdst + 3) |= (byte)(byte41 & 248); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; } }
        public byte m { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = (byte)(byte40 & 31); buf2 = buf1 >> 3; return *(byte*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(byte*)bufsrc = value; buf2 = buf1 << 3; *(byte*)bufdst |= (byte)(byte40 & 7); *((byte*)bufdst + 0) |= (byte)(byte41 & 224); byte0 = ((byte*)bufdst)[0]; } }
        public nint n { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = (byte)(byte40 & 63); buf2 = buf1 >> 5; return *(nint*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(nint*)bufsrc = value; buf2 = buf1 << 5; *(byte*)bufdst |= (byte)(byte40 & 31); *((byte*)bufdst + 0) |= (byte)(byte41 & 192); byte0 = ((byte*)bufdst)[0]; } }
        public unint o { get { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *((byte*)bufsrc + 0) = byte40; *((byte*)bufsrc + 1) = byte41; *((byte*)bufsrc + 2) = byte42; *((byte*)bufsrc + 3) = byte43; *((byte*)bufsrc + 4) = (byte)(byte44 & 31); buf2 = buf1 >> 6; return *(unint*)bufdst; } set { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *(unint*)bufsrc = value; buf2 = buf1 << 6; *(byte*)bufdst |= (byte)(byte40 & 63); *((byte*)bufdst + 4) |= (byte)(byte45 & 224); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; byte4 = ((byte*)bufdst)[4]; } }
        public int p { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte44; *((byte*)bufsrc + 1) = (byte)(byte45 & 1); buf2 = buf1 >> 5; return *(int*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(int*)bufsrc = value; buf2 = buf1 << 5; *(byte*)bufdst |= (byte)(byte44 & 31); *((byte*)bufdst + 1) |= (byte)(byte46 & 254); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; } }
        public int q { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte45; *((byte*)bufsrc + 1) = byte46; *((byte*)bufsrc + 2) = (byte)(byte47 & 31); buf2 = buf1 >> 1; return *(int*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(int*)bufsrc = value; buf2 = buf1 << 1; *(byte*)bufdst |= (byte)(byte45 & 1); *((byte*)bufdst + 2) |= (byte)(byte48 & 224); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; } }
        public int r { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = (byte)(byte47 & 63); buf2 = buf1 >> 5; return *(int*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(int*)bufsrc = value; buf2 = buf1 << 5; *(byte*)bufdst |= (byte)(byte47 & 31); *((byte*)bufdst + 0) |= (byte)(byte48 & 192); byte0 = ((byte*)bufdst)[0]; } }
        public uint s { get { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *((byte*)bufsrc + 0) = byte47; *((byte*)bufsrc + 1) = byte48; *((byte*)bufsrc + 2) = byte49; *((byte*)bufsrc + 3) = byte50; *((byte*)bufsrc + 4) = (byte)(byte51 & 63); buf2 = buf1 >> 6; return *(uint*)bufdst; } set { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *(uint*)bufsrc = value; buf2 = buf1 << 6; *(byte*)bufdst |= (byte)(byte47 & 63); *((byte*)bufdst + 4) |= (byte)(byte52 & 192); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; byte4 = ((byte*)bufdst)[4]; } }
        public uint t { get { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *((byte*)bufsrc + 0) = byte51; *((byte*)bufsrc + 1) = byte52; *((byte*)bufsrc + 2) = byte53; *((byte*)bufsrc + 3) = byte54; *((byte*)bufsrc + 4) = (byte)(byte55 & 63); buf2 = buf1 >> 6; return *(uint*)bufdst; } set { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *(uint*)bufsrc = value; buf2 = buf1 << 6; *(byte*)bufdst |= (byte)(byte51 & 63); *((byte*)bufdst + 4) |= (byte)(byte56 & 192); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; byte4 = ((byte*)bufdst)[4]; } }
        public uint u { get { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *((byte*)bufsrc + 0) = byte55; *((byte*)bufsrc + 1) = byte56; *((byte*)bufsrc + 2) = byte57; *((byte*)bufsrc + 3) = (byte)(byte58 & 31); buf2 = buf1 >> 6; return *(uint*)bufdst; } set { uint buf1, buf2; uint* bufsrc = &buf1, bufdst = &buf2; *(uint*)bufsrc = value; buf2 = buf1 << 6; *(byte*)bufdst |= (byte)(byte55 & 63); *((byte*)bufdst + 3) |= (byte)(byte59 & 224); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; } }
        public uint v { get { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *((byte*)bufsrc + 0) = byte58; *((byte*)bufsrc + 1) = byte59; *((byte*)bufsrc + 2) = byte60; *((byte*)bufsrc + 3) = byte61; *((byte*)bufsrc + 4) = (byte)(byte62 & 31); buf2 = buf1 >> 5; return *(uint*)bufdst; } set { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *(uint*)bufsrc = value; buf2 = buf1 << 5; *(byte*)bufdst |= (byte)(byte58 & 31); *((byte*)bufdst + 4) |= (byte)(byte63 & 224); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; byte4 = ((byte*)bufdst)[4]; } }
        public uint w { get { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *((byte*)bufsrc + 0) = byte62; *((byte*)bufsrc + 1) = byte63; *((byte*)bufsrc + 2) = byte64; *((byte*)bufsrc + 3) = byte65; *((byte*)bufsrc + 4) = (byte)(byte66 & 31); buf2 = buf1 >> 5; return *(uint*)bufdst; } set { ulong buf1, buf2; uint* bufsrc = (uint*)&buf1, bufdst = (uint*)&buf2; *(uint*)bufsrc = value; buf2 = buf1 << 5; *(byte*)bufdst |= (byte)(byte62 & 31); *((byte*)bufdst + 4) |= (byte)(byte67 & 224); byte0 = ((byte*)bufdst)[0]; byte1 = ((byte*)bufdst)[1]; byte2 = ((byte*)bufdst)[2]; byte3 = ((byte*)bufdst)[3]; byte4 = ((byte*)bufdst)[4]; } }
    }
}